# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageRepo: guywizards
  imageName: test-website
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'guywizards-docker-hub'
        repository: '$(imageRepo)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
- stage:
  displayName: Terraform
  jobs:
  - job: Terraform
    displayName: Terraform
    pool:
      vmImage: ubuntu-latest
    steps:    
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'Visual Studio Enterprise Subscription – MPN(a0297ccb-b2e1-4572-9ff7-85bfcea0e8bd)'
        allowTelemetryCollection: true
    - script: |
        set -e
        terraform apply -input=false -auto-approve 